### ISSUE TITLE
rUIC cannot install in R 4.2.3

### ISSUE THREAD

**Issue by KageyamaTakuya** [yutakaos/rUIC#1]
I tried to install rUIC package v0.9.0 for R v4.2.3 via package "remote" as below, however, it couldn't work.
It does not seem like other package dependencies.
How can I install this package?
Thanks,

##############################################################################################
R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.79 (8198) aarch64-apple-darwin20]

[ワークスペースが次のファイルから読み込まれました /Users/takuyakageyama/.RData]
[履歴が次のファイルから読み込まれました /Users/takuyakageyama/.Rapp.history]

> library(remotes)
> remotes::install_github("yutakaos/rUIC")
Downloading GitHub repo yutakaos/rUIC@HEAD
Running `R CMD build`...
* checking for file ‘/private/var/folders/yk/_7cc7pbd6x31q2_t28__t2vh0000gn/T/RtmpP6PVu9/remotes22a91eb8457e/yutakaos-rUIC-7bdf16e/DESCRIPTION’ ... OK
* preparing ‘rUIC’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘rUIC_0.9.0.tar.gz’
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include  -I../inst/include -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include  -I../inst/include -fPIC  -falign-functions=64 -Wall -g -O2  -c simplex_map.cpp -o simplex_map.o
clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o rUIC.so RcppExports.o simplex_map.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/yk/_7cc7pbd6x31q2_t28__t2vh0000gn/T//RtmpP6PVu9/file22a969aa41a6/rUIC_0.9.0.tar.gz’ had non-zero exit status
> 
##############################################################################################

**Comment by yutakaos** [comment]
Your error message occurs when gfortran is not installed properly (for Mac users). Check the gcc and gfortran installation for your Mac OS version.
